esphome:
  name: esphome-web-863f74
  friendly_name: Seeed-dev
  min_version: 2024.11.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Set up a wifi access point
  ap: {}

text_sensor:
  - platform: template
    name: "TCP/IP Address"
    lambda: 'return {WiFi.localIP().toString().c_str()};'
    id: tcp_ip_address

font:
  - file: "gfonts://Roboto"
    id: title
    size: 20
  - file: "gfonts://Roboto"
    id: ip_font
    size: 18

image:
  - file: mdi:white-balance-sunny
    id: icon_weather
    resize: 20x20
    type: BINARY
  - file: mdi:home-thermometer
    id: icon_temperature
    resize: 20x20
    type: BINARY
  - file: mdi:water-percent
    id: icon_humidity
    resize: 20x20
    type: BINARY
  - file: mdi:home-automation
    id: icon_devices
    resize: 20x20
    type: BINARY

i2c:
  sda: GPIO6
  scl: GPIO7
  frequency: 400kHz

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    offset_x: 0
    address: 0x3C
    id: oled_display
    lambda: |-
      it.line(0, 0, 127, 0);
      it.line(127, 0, 127, 63);
      it.line(127, 63, 0, 63);
      it.line(0, 63, 0, 0);
      it.print(0,0,id(title), "Local IP:");
      it.printf(0,20,id(ip_font), "%s", id(tcp_ip_address).state.c_str() );
      it.image(1,40,id(icon_weather));
      it.image(22,40,id(icon_temperature));
      it.image(42,40,id(icon_devices));