esphome:
  name: esphome-web-863f74
  friendly_name: Seeed-dev
  min_version: 2024.11.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio

  #Inital Lightstrip state
  on_boot:
    priority: 601
    then:
      - light.turn_on:
          id: led_strip
          brightness: 35%
          red: 0%
          blue: 100%
          green: 0%

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Set up a wifi access point
  ap: {}

light:
  - platform: esp32_rmt_led_strip
    chipset: WS2812
    rgb_order: GRB
    pin: GPIO10
    num_leds: 5
    rmt_channel: 0
    id: led_strip
    name: "My LED Strip"
    # Look at : https://github.com/ljmerza/light-entity-card - For a better Dashboard Control.
    effects:
     # Customize parameters
      - random: 
      - flicker:
      - strobe: 
      - pulse: 
      - addressable_color_wipe:
      - addressable_fireworks:
      #Custom samples  
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - lambda:
          name: "My Custom Effect"
          update_interval: 1s
          lambda: |-
            static int state = 0;
            auto call = id(led_strip).turn_on();
            // Transition of 1000ms = 1s
            call.set_transition_length(1000);
            if (state == 0) {
              call.set_rgb(1.0, 1.0, 1.0);
            } else if (state == 1) {
              call.set_rgb(1.0, 0.0, 1.0);
            } else if (state == 2) {
              call.set_rgb(0.0, 0.0, 1.0);
            } else {
              call.set_rgb(1.0, 0.0, 0.0);
            }
            call.perform();
            state += 1;
            if (state == 4)
              state = 0;
      - addressable_rainbow:
          name: "Rainbow Effect With Custom Values"
          speed: 10
          width: 50
      - flicker:
          name: "Flicker Effect With Custom Values"
          alpha: 95%
          intensity: 1.5%
      - addressable_scan:
          name: "Scan Effect With Custom Values"
          move_interval: 100ms
          scan_width: 1
      - addressable_random_twinkle:
          name: "Random Twinkle Effect With Custom Values"
          twinkle_probability: 5%
          progress_interval: 32ms