esphome:
  name: esphome-web-863f74
  friendly_name: Seeed-dev
  min_version: 2024.11.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Set up a wifi access point
  ap: {}

# Example configuration entry
output:
  - platform: ledc
    pin: GPIO02
    id: gpio_02

light:
  - platform: monochromatic
    output: gpio_02
    name: "LED filament"
    id: led_filament
 